#ifndef PROTOHACK_CONFIG_H
#define PROTOHACK_CONFIG_H

#define PROTOHACK_VERSION "0.2.0"

#define PROTOHACK_MAX_IDENTIFIER 64
#define PROTOHACK_MAX_GLOBALS 128
#define PROTOHACK_STACK_MAX 512
#define PROTOHACK_MAX_NATIVE_ARGS 8
#define PROTOHACK_MAX_LOCALS 64
#define PROTOHACK_MAX_CALL_STACK 64

#endif
