#ifndef PROTOHACK_CONFIG_H
#define PROTOHACK_CONFIG_H

#define PROTOHACK_VERSION "0.2.0"

#define PROTOHACK_MAX_IDENTIFIER 64
#define PROTOHACK_MAX_GLOBALS 128
#define PROTOHACK_STACK_MAX 512
#define PROTOHACK_MAX_NATIVE_ARGS 8
#define PROTOHACK_MAX_LOCALS 64
#define PROTOHACK_MAX_CALL_STACK 64
#define PROTOHACK_MAX_TYPE_PARAMS 8
#define PROTOHACK_MAX_SPECIALIZATIONS 256
#define PROTOHACK_MAX_EXTENSION_TRAITS 8

#ifndef PROTOHACK_ENABLE_JIT
#define PROTOHACK_ENABLE_JIT 0
#endif

#define PROTOHACK_JIT_MAX_BLOCK_OPS 128

#if PROTOHACK_ENABLE_JIT
#define PROTOHACK_JIT_PROFILE 1
#else
#define PROTOHACK_JIT_PROFILE 0
#endif

#endif
